# -*- coding: utf-8 -*-
"""Cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQxqcOLExUQFNzvoKVsukqPEdTI5bcef
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from tensorflow.keras.models import load_model

# Load saved model
model = load_model("climate_lstm.keras")

print("Model loaded successfully!")

import pandas as pd
import numpy as np
import gradio as gr
import matplotlib.pyplot as plt
import sqlite3

from sqlalchemy import create_engine
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import load_model

# Load trained model
model = load_model("climate_lstm.keras")

# Load dataset
df = pd.read_csv("climate_source1.csv")

# Climate variables
target_cols = [
    'CO2',
    'Methane',
    'Solar_Radiation',
    'Sea_level',
    'Precipitation',
    'Temperature_Anomaly'
]

print("Everything loaded successfully!")

# Scale the target columns
scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(df[target_cols])

# Number of previous years used for prediction
time_steps = 8

# Function to predict future years
def project_future(model, data_scaled, n_years, time_steps):

    future_predictions = []

    # Last 8 years
    input_seq = data_scaled[-time_steps:].copy()

    for _ in range(n_years):

        pred = model.predict(
            input_seq.reshape(
                1,
                time_steps,
                data_scaled.shape[1]
            ),
            verbose=0
        )

        future_predictions.append(pred[0])

        input_seq = np.vstack((input_seq[1:], pred))

    return np.array(future_predictions)

# Predict next 20 years
n_years = 20

future_scaled = project_future(
    model,
    data_scaled,
    n_years,
    time_steps
)

# Convert back to original values
future_pred = scaler.inverse_transform(future_scaled)

# Generate years
last_year = int(df['Year'].iloc[-1])

future_years = np.arange(
    last_year + 1,
    last_year + n_years + 1
)

# Create dataframe
future_df = pd.DataFrame(
    future_pred,
    columns=target_cols
)

future_df.insert(
    0,
    "Year",
    future_years
)

print(future_df.round(2))

# Scenario projection function
def scenario_projection(model, data_scaled, n_years, time_steps, scenario="baseline"):

    input_seq = data_scaled[-time_steps:].copy()
    future_predictions = []

    scenario_factor = {
        "baseline": 0.0,
        "high": 0.01,
        "low": -0.01
    }

    factor = scenario_factor.get(scenario, 0.0)

    for _ in range(n_years):

        pred = model.predict(
            input_seq.reshape(
                1,
                time_steps,
                data_scaled.shape[1]
            ),
            verbose=0
        )

        adjusted_pred = pred + factor * pred

        future_predictions.append(adjusted_pred[0])

        input_seq = np.vstack((input_seq[1:], adjusted_pred))

    return np.array(future_predictions)


# Predict 20 years
n_years = 20

baseline_scaled = scenario_projection(
    model, data_scaled, n_years, time_steps, "baseline"
)

high_scaled = scenario_projection(
    model, data_scaled, n_years, time_steps, "high"
)

low_scaled = scenario_projection(
    model, data_scaled, n_years, time_steps, "low"
)

# Convert to original values
baseline = scaler.inverse_transform(baseline_scaled)
high = scaler.inverse_transform(high_scaled)
low = scaler.inverse_transform(low_scaled)

# Future years
future_years = np.arange(
    df['Year'].iloc[-1] + 1,
    df['Year'].iloc[-1] + n_years + 1
)

# DataFrames
baseline_df = pd.DataFrame(
    baseline,
    columns=target_cols
)

high_df = pd.DataFrame(
    high,
    columns=target_cols
)

low_df = pd.DataFrame(
    low,
    columns=target_cols
)

baseline_df.insert(0, "Year", future_years)
high_df.insert(0, "Year", future_years)
low_df.insert(0, "Year", future_years)

print("Scenario analysis completed successfully!")