# -*- coding: utf-8 -*-
"""Cloudproject1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKCJe194SWGRw1fFon1SPuBbswGJNSvS
"""

#IMPORT LIBRARIES

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# uploading the files into the Google colab

from google.colab import files
Uploaded=files.upload()

#2 DATASET PREPARATION

#Loading the train and test dataset

data=pd.read_csv("climate_source1.csv")
df=pd.DataFrame(data)


#Exploring and previewing the dataset
print(df.head())

#checking for null values

print(df.isnull().sum())

# 3. DATA MANIPULATION
# fills the missing values
# interpolate() is used to fill missing values using nearby values
# after interpolate function the result would be float values

df['Year']=df['Year'].interpolate().astype(int)

print(df.isnull().sum())

# 4. DATA VISUALIZATION

#representing the carbon dioxide levels with respect to years
#data usage df

sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.pointplot(x='Year',y='CO2',data=df)
plt.title('Carbon Dioxide Levels by Year')
plt.xlabel('Year')
plt.ylabel('Carbon Dioxide(ppm)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Representing the Precipittion lvels with respect to years
#data usage is dg

sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.barplot(x='Year',y='Precipitation',data=df)
plt.title('Precipitation Levels by Year')
plt.xlabel('Year')
plt.ylabel('Precipitation(mm)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Representing the Solar radiation levels with respect to years
# data usage is df

sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.scatterplot(x='Year',y='Solar_Radiation',data=df)
plt.title('Soalar Radiation Levels by Year')
plt.xlabel('Year')
plt.ylabel('Solar Radiation(wm2)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Representing the Sea levels with respect to years
#data usage is df

sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.lineplot(x='Year',y='Sea_level',data=df)
plt.title('Sea Levels by Year')
plt.xlabel('Year')
plt.ylabel('Sea levels (mm)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Representing the Temperature anomalies with respect to years
#data usage is df

sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.histplot(x='Year',y='Temperature_Anomaly',data=df)
plt.title('Temperature by Year')
plt.xlabel('Year')
plt.ylabel('Temperature  (C)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#Representing Temperature anomalies
#data usage is df

sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.histplot(df['Temperature_Anomaly'],bins=20, kde=True,color='coral')
plt.title('Distribution of Temperature ')
plt.xlabel('Temperature (°C)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

import warnings
warnings.filterwarnings('ignore')

#4. DATA PREPROCESSING

from sklearn.preprocessing import MinMaxScaler

#target_cols is a lsit which contains the columns that we want to predict
#Selects the columns of interest that we want to predict
#reset_index is used to reset the index after droping the missing values

target_cols=['CO2','Methane','Solar_Radiation','Sea_level','Precipitation','Temperature_Anomaly']
df=df[['Year']+target_cols].dropna().reset_index(drop=True)

# scales all the target columns to a range like [0,1] this is essential for creating LSTM model
#fit_teansform() is used to learn the min and max values from data and applied scaling
#data_scaled is a numpy array that contains 6 target variables
# scaling transforms the data so,that it fits in a specific range usually 0 to 1

scaler=MinMaxScaler()
data_scaled=scaler.fit_transform(df[target_cols])

# 6. MODEL SELECTION AND TRAINING
# Creating a long short-term model(LSTM) is used for time series data operations

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Creating LSTM sequences ,time_steps defines a function to convert the time series data into a sequence of lengtth(time_steps=3)
# Creating a function create_sequences and passing the data,data is a scaled version of the Dataset that contains only target columns
# that we want to predict
# create sequence function transforms the time series data into sequence for LSTM
# X is the sequence of shape
# Y are the values to predict

def create_sequences(df,time_steps=3):
    X,y = [],[]
    for i in range(len(df)-time_steps):#6-3
        X.append(df[i:i+time_steps])
        y.append(df[i+time_steps])
    return np.array(X), np.array(y)


time_steps=3
X,y=create_sequences(data_scaled,time_steps)
# Splitting the data into training(80%) and testing(20%) sets
# train_size computes how many samples should go into training sets
# X is inpt data and x[:train_size] 80% goes for training input
# X[train_size:] here the remaining 20% will be testing the input
# same logic applies to the target values(y)

train_size=int(len(X)*0.8)
X_train,X_test=X[:train_size],X[train_size:]# here, X_train is 80% past sequence(inputt) is used to tarin the lstm
y_train,y_test=y[:train_size],y[train_size:]# y_train is 80% of the corresponding future values,targets for training
                                                #x_test is 20% of remaining sequence, is used to test how well the model works                                  #y_test is 20% of corresponding future values,is used for evaluation
# we are building a neural network using keras(tensorflow) to predict multiple output
# Sequential() it creates a sequencial model layers are stacked one after the otherr
# model.add,adds an LSTM layers with 64 units


model=Sequential()
model.add(LSTM(64,input_shape=(time_steps,len(target_cols))))# time_steps,3 years at a time,len(target_cols ), indicates how many features for predicting
model.add(Dense(len(target_cols)))  # output layer Dense(),means it id fully connected layer ,len(target_cols),model predicts 6 variables at once
model.compile(optimizer='adam',loss='mse')# optimiser a fast, efficient algorithm for adjusting weights
# mse a common loss function for regression

# x_train,y_trains ths trains the lstm model on training data to learn how to predict multiple climate variables
# epochs=100 this model will go through training data 100 times
# barch_size=4 the data is split into mini batches of 4 samples
# validation_aplit=0.1 10% of the training data is held out as validation set
# verbose=0 controls how much output is shown during training

model.fit(X_train,y_train,epochs=200,batch_size=4,validation_split=0.1,verbose=1)

# y_pted_scaled gives scaled output because the model was trained on scaled data
# y_pred converts the scaled predicted values back to the original scale without this the predicted values will be 0-1
# y_true this converts an actual values from scaled form back to the original real-world values

y_pred_scaled=model.predict(X_test)
y_pred=scaler.inverse_transform(y_pred_scaled)
y_true=scaler.inverse_transform(y_test)

# test_years extracts thn last n year from the year columns these year are used as x-axis
# len(y_true) nummber of test samples

test_years=df['Year'].iloc[-len(y_true):].values

# creating a large plot with respect to number of target columns(6)
# loops through number of target columns

plt.figure(figsize=(15,4*len(target_cols)))
for i,col in enumerate(target_cols):
    plt.subplot(len(target_cols), 1,i+1)
    plt.plot(test_years,y_true[:,i],label='Actual',marker='o')# plots for the actual values
    plt.plot(test_years,y_pred[:,i],label='Predicted',marker='x')# plots for the predicted values
    plt.title(f'{col}: Actual vs Predicted')
    plt.xlabel('Year')
    plt.ylabel(col)
    plt.legend()

plt.tight_layout()
plt.show()

#7. MODEL EVALUATION
# mse tells how far the predictions from the actual values
 #y_true actual values of ith variable, y_pred predicted values of ith variabley_pred predicted values of ith variable
print("Mean Squared Error for each variable")
for i,col in enumerate(target_cols):
    mse = mean_squared_error(y_true[:, i],y_pred[:, i])
    print(f"{col}: {mse:.4f}")

#8. FUTURE PROJECTIONS
#MinMaxScalar is used for scaling data between 0 and 1
#sequential creates a deep learning model
#LSTM- Long Short Term Memory layer used for predicting climate change prediction
#Dense - fully connected output layer
#dropout- prevents over fitting

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

#time_steps uses 8 yrs to predict future yrs
time_steps=8

#MinMaxScalar creates a scalar object
scaler=MinMaxScaler()
#fit_transform() learns the min &max of each column
#scales data between 0 and 1
data_scaled=scaler.fit_transform(df[target_cols])

#creating a sequence
#year 1-8 used to predict year 9
#year 2-9 used to predict year 10
def create_sequences(df,time_steps):
    X,y=[],[]
    for i in range(len(data)-time_steps):
        X.append(df[i:i+time_steps])
        y.append(df[i+time_steps])
    return np.array(X), np.array(y)

#x is past 8 yrs
#y is next yrs values
X,y=create_sequences(data_scaled,time_steps)

# 9. Dividing the dataset into training and testing sets
# train sets contains 80% dataset
# test sets contains 20% dataset

train_size=int(len(X)*0.8)
X_train,X_test=X[:train_size],X[train_size:]
y_train,y_test=y[:train_size],y[train_size:]


# 10. Building a LSTM model

#creates a empty neural network
model=Sequential()
#First LSTM layer with 64 neurons
#return_sequence=true; because, another LSTM layer comes after the first layer
model.add(LSTM(64,return_sequences=True,input_shape=(time_steps,len(target_cols))))
#Dropout: drops 20% of neurons randomly. Prevents over fitting
model.add(Dropout(0.2))

# Second lstm layer with 32 neurons
#no return sequence=true because, this is the last lstm layer
model.add(LSTM(32))
#Dropout: drops 20% of neurons randomly
model.add(Dropout(0.2))
#outputs one value for each variable for 6 variables 6 outputs
model.add(Dense(len(target_cols)))

#compiling the model
# adam = smart optimize , loss=mse mean squared error used for regression
model.compile(optimizer='adam',loss='mse')

# training model
# epochs=300 : model sees the dataset 300 times
# batch_size=4: updates the weight for every 4 samples
# verbose=1 : shows training progress
model.fit(X_train,y_train,epochs=300,batch_size=4,verbose=1)

# Save the trained model
model.save("climate_lstm.h5")

print("Model saved successfully!")
# project future: function to predict future yrs

def project_future(model,data_scaled,n_years,time_steps):

    # Future predictions: an empty list is used to store predictions
    future_predictions=[]
    # takes last 8 yrs as input
    input_seq=data_scaled[-time_steps:].copy()
    # repeat the prediction for number of future years
    for _ in range(n_years):
        # input is reshaped to (1,sample,8 years,features)
        pred=model.predict(input_seq.reshape(1,time_steps,data_scaled.shape[1]),verbose=0)
        future_predictions.append(pred[0])
        # Removes oldest year and adds predicted year so, that prediction becomes input for next prediction
        # This is called recursive multi step forecasting
        input_seq=np.vstack((input_seq[1:],pred))
    # returns the predicted values
    return np.array(future_predictions)

#predicts next 20 future years (scaled values)
n_years=20
future_scaled=project_future(model,data_scaled,n_years,time_steps)
# converting the scaled values(0-1) to real values such as co2, sea level etc
future_pred=scaler.inverse_transform(future_scaled)

#generating future years
# the last year is 2011
# future years starts from 2012,2013,2014....
last_year=int(df['Year'].iloc[-1])
future_years=np.arange(last_year+1,last_year+n_years+1)

# creating a final dataframe
# dataframe: 0, Year, co2, methane.....
future_df=pd.DataFrame(future_pred,columns=target_cols)
future_df.insert(0,'Year',future_years)

#printing rounded results
print(future_df.round(2))

import os

print(os.listdir())

actual_df = df[(df['Year']>=2000) & (df['Year']<=2011)]
pred_df   = future_df[(future_df['Year']>=2012) & (future_df['Year']<=2031)]

plt.figure(figsize=(15,4*len(target_cols)))

for i, col in enumerate(target_cols):
    plt.subplot(len(target_cols), 1, i+1)

    plt.plot(actual_df['Year'], actual_df[col],
             label='Actual (2000-2011)', marker='o')

    plt.plot(pred_df['Year'], pred_df[col],
             label='Predicted (2012-2031)', marker='x', linestyle='--')

    plt.title(f'{col}: Actual vs Predicted')
    plt.xlabel('Year')
    plt.ylabel(col)
    plt.legend()
    plt.grid(True)

plt.tight_layout()
plt.show()

#11. SCENARIO ANALYSIS
# defining scenario projection function
# arguments: model: trained lstm model
# data_scaled: scaled dataset after minmaxscalar
# n_years : number of future years to predict
# time_steps: number of past years the model uses for prediction
# scenario : defines the baseline, high and low emissions

def scenario_projection(model,data_scaled,n_years,time_steps,scenario="baseline"):
    # takes the last time_steps rows from the scaled dataset
    # this becomes the starting input for future prediction
    # .copy() : prevents modifying original data
    input_seq=data_scaled[-time_steps:].copy()
    # future_predictions : creating an empty list which stores all predicted future values
    future_predictions=[]


    # dictionary that defines
    # 1. Baseline: 0 changes
    # 2. High : increases the prediction by 1%
    # 3. Low : decreases the prediction by 1%
    scenario_factor = {
        "baseline":0.0,
        "high":0.01,
        "low":-0.01
    }
    # gets the factor based on the selected scenario. If the scenario not found default is 0.0
    factor=scenario_factor.get(scenario,0.0)

    # each loop predicts one future year
    for _ in range(n_years):
        # reshaping input to match lstm format: (samples,time_steps,features)
        # predicts next year's values
        pred=model.predict(input_seq.reshape(1,time_steps,data_scaled.shape[1]),verbose=0)
        # applying the scenario adjustments like high and low emissions
        adjusted_pred=pred+factor*pred
        # adds predicted values to the list
        # [0] removes extra dimension
        future_predictions.append(adjusted_pred[0])
        # updating input sequence
        # removes the oldest year input_seq[1:]
        # adds new predicted year at bottom this creates a rolling window
        # so, the prediction keeps moving forward year by year
        input_seq=np.vstack((input_seq[1:],adjusted_pred))
    # converts the list to numpy array. Returns the predicted future values
    return np.array(future_predictions)

# 20 future years
n_years=20
# runs predictions for: baseline, high emissions and low emissions
baseline_scaled=scenario_projection(model,data_scaled,n_years, time_steps,"baseline")
high_scaled=scenario_projection(model,data_scaled,n_years,time_steps,"high")
low_scaled=scenario_projection(model,data_scaled,n_years,time_steps,"low")

# converting the scaled predictions back to real climate values
baseline=scaler.inverse_transform(baseline_scaled)
high=scaler.inverse_transform(high_scaled)
low=scaler.inverse_transform(low_scaled)

future_years=np.arange(df['Year'].iloc[-1]+1,df['Year'].iloc[-1]+n_years+1)

# converting predictions into structured dataframe
baseline_df=pd.DataFrame(baseline,columns=target_cols)
high_df=pd.DataFrame(high,columns=target_cols)
low_df=pd.DataFrame(low,columns=target_cols)

baseline_df.insert(0,"Year",future_years)
high_df.insert(0,"Year",future_years)
low_df.insert(0,"Year",future_years)

for col in target_cols:

    if col in baseline_df.columns and col in high_df.columns and col in low_df.columns:

        plt.figure(figsize=(20,2*len(target_cols)))

        plt.plot(baseline_df["Year"], baseline_df[col],
                 label="Baseline Scenario")

        plt.plot(high_df["Year"], high_df[col],
                 linestyle="--", label="High Emission Scenario")

        plt.plot(low_df["Year"], low_df[col],
                 linestyle="--", label="Low Emission Scenario")

        plt.title(f"{col} - Scenario Analysis")
        plt.xlabel("Year")
        plt.ylabel(col)
        plt.legend()
        plt.grid(True)

        plt.show()

    else:
        print(f"{col} not found in one of the scenario dataframes.")

import matplotlib.pyplot as plt
import gradio as gr

def generate_plot():
    actual_df = df[(df['Year'] >= 2000) & (df['Year'] <= 2011)]
    pred_df   = future_df[(future_df['Year'] >= 2012) & (future_df['Year'] <= 2111)]

    save_path = "/content/future_prediction.png"

    plt.figure(figsize=(15,4* len(target_cols)))

    for i, col in enumerate(target_cols):
        plt.subplot(len(target_cols), 1, i + 1)

        plt.plot(actual_df['Year'], actual_df[col],
                 label='Actual (2000-2011)', marker='o')

        plt.plot(pred_df['Year'], pred_df[col],
                 label='Predicted (2012-2031)', marker='x', linestyle='--')

        plt.title(f'{col}: Actual vs Predicted')
        plt.xlabel('Year')
        plt.ylabel(col)
        plt.legend()
        plt.grid(True)

    plt.tight_layout()
    plt.savefig(save_path, bbox_inches="tight")
    plt.close()

    return save_path

def generate_scenario_plot():
    save_path = "/content/scenario_analysis.png"

    valid_cols = [
        col for col in target_cols
        if col in baseline_df.columns and col in high_df.columns and col in low_df.columns]

    plt.figure(figsize=(15, 4*len(valid_cols)))

    for i, col in enumerate(valid_cols):
        plt.subplot(len(valid_cols), 1, i+1)

        plt.plot(baseline_df["Year"], baseline_df[col],
                 label="Baseline Scenario")

        plt.plot(high_df["Year"], high_df[col],
                 linestyle="--", label="High Emission Scenario")

        plt.plot(low_df["Year"], low_df[col],
                 linestyle="--", label="Low Emission Scenario")

        plt.title(f"{col} - Scenario Analysis")
        plt.xlabel("Year")
        plt.ylabel(col)
        plt.legend()
        plt.grid(True)

    plt.tight_layout()
    plt.savefig(save_path, bbox_inches="tight")
    plt.close()

    return save_path

!pip install gradio
# installing gradio library used to create web interface directly from python
# gr creates an interactive web app
# sqlite3 connects sqlite database
# create_ engine it's a database connection using sqlalchemy

import gradio as gr
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

# creating sqlite database named climate prediction used to store predictions
engine=create_engine("sqlite:///climate_prediction.db")

# converting year column to integer
df['Year']=df['Year'].astype(int)
future_df['Year']=future_df['Year'].astype(int)

# creating a target_cols list contains climate variables
target_cols=['CO2','Methane','Solar_Radiation','Sea_level','Precipitation','Temperature_Anomaly']

# it's a prediction and storage function
# this function runs when the user clicks the submitt
def predict_and_store(variable,year):
    # ensuring that the entered year is integer
    year=int(year)
    # initialising variables
    result_text=""
    value=None
    data_type=""

    # searching entered year inside the historical dataset
    # Historical check
    historical=df[df['Year']==year]
    # if historical data exists
    if not historical.empty:
         # gets the climate value
        value=historical[variable].values[0]
        data_type="Historical"
        # creating a output result message
        result_text=f"Historical {variable} value in {year}: {value}"

    else:
        # checking future prediction
        future=future_df[future_df['Year']==year]

        if not future.empty:
            value=future[variable].values[0]
            data_type="Predicted"
            result_text=f"Predicted {variable} value in {year}: {value}"
        else:
            return "🫣🫣Year not found!🫣🫣"

    # stored the result into database
    # creating a table row containing: year, variables,value and datatype
    result_df=pd.DataFrame({
        "Year":[year],
        "Variable":[variable],
        "Value":[value],
        "Type":[data_type]
    })
    # saves into the sqlite database
    # table name climate prediction
     # appends new record does not over write the data
    result_df.to_sql(
        name="climate_predictions",
        con=engine,
        if_exists="append",
        index=False
    )
     # returns the result to user interface
    # displays the prediction in textbox
    return result_text

# view stored result function
def view_results():
     # connecting database
    conn=sqlite3.connect("climate_prediction.db")
    # executes the query and fetches all the stored predictions
    query="SELECT * FROM climate_predictions"
    data=pd.read_sql(query,conn)
    # closing connection
    conn.close()
     # returns the data shows the table in dashboard
    return data

# deletes the stored predictions
def clear_database():

    conn=sqlite3.connect("climate_prediction.db")
     # creating a cursor object
    cursor=conn.cursor()
     #Removes all rows
    cursor.execute("DELETE FROM climate_predictions")
     # saves all changee
    conn.commit()
    conn.close()
    # returns the delete message
    return "All stored results cleared!"

from google.colab import drive
drive.mount('/content/drive')

video_path = "/content/drive/MyDrive/Background.mp4"
gr.set_static_paths(paths=[video_path])

custom_css="""
.bg-video {
    width: 100vw;
    height: 100vh;
    object-fit:cover;
    pointer-events: none;
}
.video-wrapper {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index:-1 ;
    overflow: hidden;
}

.video-wrapper video {
    position: absolute;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 100%;
    width: auto;
    height: auto ;
    transform: translate(-50%, -50%);
    object-fit: cover;
}


.gradio-container,
.gradio-container > div {
    margin: 0;
    padding: 0;
    min-height: 100vh;
}
@media (max-width: 768px) {
    .gradio-container .gr-row {
        flex-direction: column;
    }
     #main-row{
       flex-direction:column;
}
}

.gradio-container{
    background:linear-gradient(135deg,#1f4037,#99f2c8);
    min-height:100vh;
    border-radius:15px;
    box-shadow:0px 8px 25px rgba(0,0,0,0.2);
    padding:0px;
}

#main-row {
    display: flex;
    position:relative;
    flex-direction: row;
    flex-wrap: wrap;
    width: 100% ;
    z-index:2;
    justify-content:flex-start;
}


#left-panel {
    width:800px;
    min-width:400px;
    border:5px solid white;
    border-radius:25px;
    margin-left:0px;
    padding:25px;
}


.gradio-container .wrap label {
    font-size:18px;
    font-weight:bold;
    color:#ffffff;
}


.gradio-container .wrap span {
    font-size:16px;
    font-weight:bold;
    color:black;
}

textarea,input{
    border-radius:10px;
    border:2px solid #4CAF50;
    padding:10px;
    font-size:18px;
}


textarea:focus,input:focus{
    border-color:#ff9800;
    box-shadow:0 0 8px #ff9800;
}


h1{
   margin-top:5px;
   text-align:center;
    color:white;
    font-weight:bold;
    font-size:35px;
    border:3px solid white;
    border-radius:20px;
}
h6{
    text-align:center;
    color:white;
    font-weight:bold;
    font-size:25px;
    border:3px solid white;
    border-radius:20px;
}


button{
    background-color:#4CAF50;
    color:white;
    border-radius:10px;
    font-size:16px;

}

@media (max-width: 768px) {
    #main-row {
        flex-direction: column;
    }
#main-row > div:first-child {
    width:250px;
    min-width:300px;
    flex: 0 0 auto;
}
    #left-panel {
        width: 900px;
        min-width: 900px;
        max-width: 900px;
        flex: 0 0 900px;

         border: 5px solid white;
         border-radius: 25px;
         padding: 25px;
    }
}

#main-btn{
       border:1px solid white;
       background:#4CAF50;
       color:white;
       border-radius:25px;
       font-size:15px;
       width:200px;
       align-items:center;
       justify-content:center;
       margin:0px;
       margin-left:60px;
}
 #left-panel {
        width: 400px;
        min-width: 400px;
        max-width: 400px;
        flex: 0 0 400px;
         border: 5px solid white;
         border-radius: 25px;
         padding: 25px;
    }
"""

def clear_images():
    return None, None

gr.close_all()

# creating a gradio interface
# creating dashboard layout
with gr.Blocks(css=custom_css) as demo:
     # title: displays heading
  with gr.Row(elem_id="main-row"):
   gr.HTML(f"""
    <div class="video-wrapper">
        <video class="bg-video" autoplay muted loop playsinline preload="auto">
            <source src="/gradio_api/file={video_path}" type="video/mp4">
        </video>
    </div>
    """)
   with gr.Column(elem_id="left-panel"):
    gr.Markdown("<h1> 🌍🌏Climate Prediction Dashboard🌏🌎</h1>")
    # shows the year range
    gr.Markdown("""<h6>
   📗📙📔Historical Data:1980 to 2011<br>
   🎩🎩🎩Predicted Data:2012 to 2031
    </h6>""")

    # Inputs
     # user selects climate variable to be predicted
    variable_input=gr.Dropdown(
        choices=target_cols,
        label="Select Climate Variable",

    )
    # user enter year
    year_input=gr.Number(label="Enter Year")

    # buttons
    # predict
    submit_btn=gr.Button("Submitt",elem_id="main-btn")
    # view database
    view_btn=gr.Button("View Stored Results",elem_id="main-btn")
    # clear database
    clear_btn=gr.Button("Clear Stored Results",elem_id="main-btn")
    show_btn=gr.Button("Show future projections",elem_id="main-btn")
    scenario_btn=gr.Button("Show scenario projection",elem_id="main-btn")
    clear_img_btn = gr.Button("Clear Images",elem_id="main-btn")

    # Outputs
    output_text = gr.Textbox(label="Prediction Output")
    output_table = gr.Dataframe()
    clear_output = gr.Textbox(label="Database Status")

    gr.Markdown("<h6>Future Projection Plot</h6>")
    out_img=gr.Image(type="filepath")

    gr.Markdown("<h6>Scenario Projection Plot</h6>")
    scenario_out=gr.Image(type="filepath")

    # Button Actions
    submit_btn.click(
        fn=predict_and_store,
        inputs=[variable_input, year_input],
        outputs=output_text
    )

    view_btn.click(
        fn=view_results,
        inputs=[],
        outputs=output_table
     )

    clear_btn.click(
         fn=clear_database,
         inputs=[],
         outputs=clear_output
     )

    show_btn.click(
          fn=generate_plot,
          inputs=None,
          outputs=out_img
      )

    scenario_btn.click(
           fn=generate_scenario_plot,
           inputs=None,
           outputs=scenario_out
     )

    clear_img_btn.click(
          fn=clear_images,
          inputs=[],
          outputs=[out_img, scenario_out]
      )

demo.launch()

from google.colab import files

files.download("climate_lstm.keras")